// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ziihwvmenujirdaptbcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppaWh3dm1lbnVqaXJkYXB0YmN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2NTY0MjQsImV4cCI6MjA3OTIzMjQyNH0.pythCiYY_UZfdezgNpWWM6hqm6-nX35zJwSWuXjAB-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});